version: '3.9'
services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
  proxy:
    build:
      context: proxy/
      dockerfile: Dockerfile
    ports:
      - 80:80